Repository wecode-bootcamp-korea/21-1st-Biskit-frontend, pull requests merged in 2021-06, with the labels that each got.

#1 Add : Nav
  public/images/common/icon/README.md
  public/images/common/icon/basket.png
  public/images/common/icon/logo.png
  public/images/common/icon/search.png
  src/Components/Nav/ListMenu.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/gnb_util.js
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청

#3 [21기 전건우] Modify : 로그인 레이아웃, 기능 추가 & 공통 nav style 부분 변경 (1차 코드 리뷰 반영)
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/ListMenu.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavConst/GnbMenu.js
  src/Components/Nav/NavConst/ListMenu.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Routes.js
  src/Styles/_variables.scss
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#4 [21기 전건우] Modify: 회원가입 페이지 레이아웃, 기능 추가 (2차 코드 리뷰 반영)
  public/data/Signup/signup.js
  public/images/Main/food1.jpeg
  public/images/Signup/Required.gif
  src/Components/Nav/Nav.scss
  src/Components/Signup/SignupComponents/Components/SignInputTermsBox/SignInputTermsBox.js
  src/Components/Signup/SignupComponents/Components/SignInputTermsBox/SignInputTermsBox.scss
  src/Components/Signup/SignupComponents/Components/SignupInputWrap/SignupInputWrap.js
  src/Components/Signup/SignupComponents/Components/SignupInputWrap/SignupInputWrap.scss
  src/Components/Signup/SignupComponents/DataComponents/AcceptTerms.js
  src/Components/Signup/SignupComponents/DataComponents/AcceptTerms.scss
  src/Components/Signup/SignupComponents/DataComponents/PrivacyConsent.js
  src/Components/Signup/SignupComponents/DataComponents/PrivacyConsent.scss
  src/Components/Signup/SignupConst/FirstPhoneNumber.js
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Styles/_variables.scss
  src/Styles/reset.scss
Labels: Status: Conflict 해결 요청

#5 [21기 신미영] Modified: 2차 리뷰 수정 사항 반영 완료
  public/data/ProdDetail/picturesData.js
  public/data/ProdDetail/picturesData.json
  public/data/ProdDetail/prodDetail.json
  public/data/ProdDetail/prodDetailData.json
  public/data/ProdDetail/review.json
  public/images/ProdDetail/delivery.png
  public/images/ProdDetail/detail.jpeg
  public/images/ProdDetail/like-icon.png
  public/images/ProdDetail/main1.JPG
  public/images/ProdDetail/main2.jpg
  public/images/ProdDetail/main3.jpg
  public/images/ProdDetail/main4.jpeg
  public/images/ProdDetail/main5.jpeg
  public/images/ProdDetail/question-icon.png
  public/images/ProdDetail/recipe-icon.png
  public/images/ProdDetail/refund.png
  public/images/ProdDetail/share-icon.png
  public/images/ProdDetail/unlike-icon.png
  src/Components/ProdDetail/OrderInformation/OrderInformation.js
  src/Components/ProdDetail/OrderInformation/bodyOrderInformation.scss
  src/Components/ProdDetail/OrderInformation/headOrderInformation.scss
  src/Components/ProdDetail/ProductPictures/ProductPictures.js
  src/Components/ProdDetail/ProductPictures/productPictures.scss
  src/Components/ProdDetail/TapContents/DeliveryRefund.js
  src/Components/ProdDetail/TapContents/Description.js
  src/Components/ProdDetail/TapContents/Information.js
  src/Components/ProdDetail/TapContents/Review.js
  src/Components/ProdDetail/TapContents/deliveryRefund.scss
  src/Components/ProdDetail/TapContents/description.scss
  src/Components/ProdDetail/TapContents/information.scss
  src/Components/ProdDetail/TapContents/review.scss
  src/Components/ProdDetail/TapList/TapList.js
  src/Components/ProdDetail/TapList/TapList.scss
  src/Data/weekname.js
  src/Pages/ProdDetail/ProdDetail.js
  src/Pages/ProdDetail/ProdDetail.scss
  src/Pages/ProdDetail/prodDetail.scss
  src/Routes.js
  src/Styles/_mixin.scss
Labels: Status: 리뷰 요청

#9 Add: [21기 권오현] 장바구니 연동
  src/Pages/Login/Login.js
  src/Pages/MenuList/DaysBtn.js
  src/Pages/MenuList/List.js
  src/Pages/MenuList/MenuList.js
  src/Pages/MenuList/MenuList.scss
  src/Pages/MenuList/ReadMe.md
  src/Pages/MenuList/ThemeBtn.js
  src/Pages/MenuList/list.scss
Labels: Status: 리뷰 요청

#10 Add : 메인 패치 통신 완료
  src/Components/Main/BestWrap/BestWrap.js
  src/Components/Main/BestWrap/BestWrap.scss
  src/Components/Main/BestWrap/ProdList.js
  src/Components/Main/RecommendWrap/RecommendWrap.js
  src/Components/Main/RecommendWrap/RecommendWrap.scss
  src/Components/Main/RecommendWrap/SlideContents/RecommendSlideCount.js
  src/Components/Main/RecommendWrap/SlideContents/RecommendWrapConst/GnbMenu.js
  src/Components/Main/RecommendWrap/SlideContents/SlideContents.js
  src/Components/Main/ReviewWrap/ReviewWrap.js
  src/Components/Main/ReviewWrap/ReviewWrap.scss
  src/Components/Main/ReviewWrap/SlideContents/CommentContents.js
  src/Components/Main/ReviewWrap/SlideContents/ImgContents.js
  src/Components/Main/ReviewWrap/SlideContents/ReviewList/ImgCount.js
  src/Components/Signup/SignupComponents/Components/SignupInputWrap/SignupInputWrap.js
  src/Pages/Main/Main.js
  src/Pages/ProdDetail/ProdDetail.js
  src/Pages/ProdDetail/prodDetail.scss
  src/Pages/Signup/Signup.js
Labels: Status: 리뷰 요청

#12 Fix: 테마 필터 index 수정
  src/Pages/MenuList/MenuListTheme.js
Labels: Status: 리뷰 요청

#11 [21기 신미영] Modified: fetch 관련 내용 수정
  src/Components/ProdDetail/OrderInformation/OrderInformation.js
  src/Components/ProdDetail/ProductPictures/ProductPictures.js
  src/Components/ProdDetail/TapContents/DeliveryRefund.js
  src/Components/ProdDetail/TapContents/Description.js
  src/Components/ProdDetail/TapContents/Information.js
  src/Components/ProdDetail/TapContents/Review.js
  src/Pages/ProdDetail/ProdDetail.js
  src/Pages/ProdDetail/prodDetail.scss
Labels: Status: 수정 요청

#13 Add: [21기 권오현] 페이지네이션 버튼 수정
  src/Pages/MenuList/MenuList.js
  src/Pages/MenuList/MenuListTheme.js
Labels: Status: 리뷰 요청

#8 [전건우] Add : 장바구니 기능 구현 선택체크, 전체체크, 리스트 삭제 부분완료
  public/data/Cart/cartData.json
  public/favicon.ico
  public/images/Cart/exclamation.png
  public/images/Cart/order.png
  public/images/Cart/payment.png
  public/images/Cart/shopping-cart.png
  public/images/Cart/unSelectedButton.png
  public/index.html
  src/Components/Cart/EmptyCart/EmptyCart.js
  src/Components/Cart/EmptyCart/emptyCart.scss
  src/Components/Cart/ShoppingProduct/ShppingProduct.js
  src/Components/Cart/ShoppingProduct/shoppingProduct.scss
  src/Components/Main/GridWrap/GridWrap.js
  src/Components/ProdDetail/ProductPictures/ProductPictures.js
  src/Components/ProdDetail/TapContents/.Review.js.swp
  src/Components/ProdDetail/TapContents/DeliveryRefund.js
  src/Components/ProdDetail/TapContents/Description.js
  src/Components/ProdDetail/TapContents/Information.js
  src/Components/ProdDetail/TapContents/Review.js
  src/Components/ProdDetail/TapList/TapList 2.js
  src/Components/ProdDetail/TapList/TapList 2.scss
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/MenuList/List.js
  src/Pages/MenuList/MenuList.js
  src/Pages/ProdDetail/ProdDetail.js
  src/Pages/ProdDetail/prodDetail.scss
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
